# Generated by Django 3.1 on 2020-08-06 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_mar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mar', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_pro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pro', models.CharField(max_length=30)),
                ('cantidad_pro', models.IntegerField()),
                ('precio_pro', models.FloatField()),
                ('existencia_pro', models.BooleanField()),
                ('marca_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.marca')),
            ],
        ),
    ]
